name: Bug Report
description: File an lrzip-next bug report
title: ":lady_beetle: [Insert Bug Title Here]"
labels: [bug]
assignees:
  - pete4abw
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!\
        Please make sure there is not already an issue filed for this.
  - type: input
    attributes:
      label: lrzip-next Version
      description: What version of lrzip-next are you running?
      placeholder: Provide output of lrzip-next -V
    validations:
      required: true
  - type: input
    attributes:
      label: lrzip-next command line
      description: |
          Enter the full lrzip-next command line. Be sure to use -vv.
          If you have an lrzip.conf file, please attach it in the next section below.
      placeholder: lrzip-next -vv...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
      description: Explain in detail what went wrong?
      placeholder: |
          As complete a description as possible...
          Segfault?
          Corrupt File?
          Performance Issue?
          Something unexpected?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What was expected behavior?
      description: Explain in detail what should have happened?
      placeholder: As complete a description as possible...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Exactly what steps did you take leading up to the bug?
      placeholder: |
          As complete a description as possible...
          Steps
          1.
          2.
          3.
          4.
    validations:
      required: true      
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations: 
      required: false
  - type: textarea
    attributes:
      label: Please provide system details
      description: Provide system details such as OS Distro, Kernel version, System Ram etc.
      value: |
         OS Distro: 
         Kernel Version (uname -a): 
         System ram (free -h): 
    validations: 
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Screenshots, POC files, config files, or any other relevant info
      placeholder: Add any additional info, files, etc. here.
